spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mjx?characterEncoding=UTF-8
    username: root
    password: ROOT
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false


#server:
#  port: 8888

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.milotnt.pojo